#!/bin/bash
# Generated by prepare_prune_batches_v4.py

echo 'Starting pruning batches v4...'
python3 prune_candidates.py --results batches_prune_v4/batch_0.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_0.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_1.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_1.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_2.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_2.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_3.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_3.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_4.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_4.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_5.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_5.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_6.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_6.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_7.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_7.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_8.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_8.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_9.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_9.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_10.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_10.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_11.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_11.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_12.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_12.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_13.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_13.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_14.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_14.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_15.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_15.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_16.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_16.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_17.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_17.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_18.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_18.txt 2>&1 &
python3 prune_candidates.py --results batches_prune_v4/batch_19.json --output-dir candidates_v4 --verbose > batches_prune_v4/log_19.txt 2>&1 &
wait
echo 'All batches complete.'
