#!/bin/bash
# Generated by prepare_prune_batches.py

echo 'Starting pruning batches...'
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_0.json --output-dir candidates_pruned --verbose > batches_prune/log_0.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_1.json --output-dir candidates_pruned --verbose > batches_prune/log_1.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_2.json --output-dir candidates_pruned --verbose > batches_prune/log_2.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_3.json --output-dir candidates_pruned --verbose > batches_prune/log_3.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_4.json --output-dir candidates_pruned --verbose > batches_prune/log_4.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_5.json --output-dir candidates_pruned --verbose > batches_prune/log_5.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_6.json --output-dir candidates_pruned --verbose > batches_prune/log_6.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_7.json --output-dir candidates_pruned --verbose > batches_prune/log_7.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_8.json --output-dir candidates_pruned --verbose > batches_prune/log_8.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_9.json --output-dir candidates_pruned --verbose > batches_prune/log_9.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_10.json --output-dir candidates_pruned --verbose > batches_prune/log_10.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_11.json --output-dir candidates_pruned --verbose > batches_prune/log_11.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_12.json --output-dir candidates_pruned --verbose > batches_prune/log_12.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_13.json --output-dir candidates_pruned --verbose > batches_prune/log_13.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_14.json --output-dir candidates_pruned --verbose > batches_prune/log_14.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_15.json --output-dir candidates_pruned --verbose > batches_prune/log_15.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_16.json --output-dir candidates_pruned --verbose > batches_prune/log_16.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_17.json --output-dir candidates_pruned --verbose > batches_prune/log_17.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_18.json --output-dir candidates_pruned --verbose > batches_prune/log_18.txt 2>&1 &
python3 pymotifscan/prune_candidates.py --results batches_prune/batch_19.json --output-dir candidates_pruned --verbose > batches_prune/log_19.txt 2>&1 &
wait
echo 'All batches complete.'
