import json
import os
import math
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('results_file', default='merged_results.json', nargs='?', help='Path to merged_results.json')
    parser.add_argument('--num-batches', type=int, default=20)
    parser.add_argument('--output-dir', default='batches_prune')
    parser.add_argument('--target-dir', default='candidates_pruned')
    args = parser.parse_args()

    print(f"Reading {args.results_file}...")
    with open(args.results_file) as f:
        data = json.load(f)
    
    results = data.get('results', {})
    
    # Calculate complexity (number of models) for each key
    key_complexities = []
    for k, v in results.items():
        count = len(v.get('models', []))
        key_complexities.append((k, count))
    
    # Sort by complexity descending (LPT - Longest Processing Time first)
    key_complexities.sort(key=lambda x: x[1], reverse=True)
    
    total = len(key_complexities)
    print(f"Splitting {total} signatures into {args.num_batches} batches (Round-Robin distribution)...")
    
    # Initialize batches
    batches = [{} for _ in range(args.num_batches)]
    
    # Distribute round-robin
    for i, (k, count) in enumerate(key_complexities):
        batch_idx = i % args.num_batches
        batches[batch_idx][k] = results[k]

    os.makedirs(args.output_dir, exist_ok=True)
    bash_lines = []
    
    for i in range(args.num_batches):
        chunk_data = {
            "metadata": data.get("metadata", {}),
            "results": batches[i]
        }
        
        batch_file = os.path.join(args.output_dir, f"batch_{i}.json")
        with open(batch_file, 'w') as f:
            json.dump(chunk_data, f, indent=2)
            
        # Command for this batch
        log_file = os.path.join(args.output_dir, f"log_{i}.txt")
        # Run in parallel
        cmd = f"python3 pymotifscan/prune_candidates.py --results {batch_file} --output-dir {args.target_dir} --verbose > {log_file} 2>&1"
        bash_lines.append(cmd)

    run_script = "run_prune_batches.sh"
    with open(run_script, "w") as f:
        f.write("#!/bin/bash\n")
        f.write("# Generated by prepare_prune_batches.py\n\n")
        f.write("echo 'Starting pruning batches...'\n")
        
        for line in bash_lines:
            f.write(f"{line} &\n")
            
        f.write("wait\n")
        f.write("echo 'All batches complete.'\n")
        
    os.chmod(run_script, 0o755)
    print(f"Generated {run_script}")

if __name__ == "__main__":
    main()
