# Detailed H-bond spot-check visualization
# Generated by detailed_energy_spot_checks.py

from pymol.cgo import *
from pymol import cmd
from pymol import util

# Settings
cmd.set('stick_radius', 0.15)
cmd.set('sphere_scale', 0.25)
cmd.set('label_size', 14)
cmd.set('label_color', 'white')
cmd.set('float_labels', 'on')
cmd.set('label_position', (0, 0, 3))

# Candidate 1: candidates_v2/F5_ASP_SC/N_plus_N_plus_N_plus_N_plus_N.pdb model 1
# delta_hbond: -7.345, delta_fa_rep: 2.400
# Interfacial H-bonds: 5, Total energy: -7.345
cmd.load('spot_check_pdbs/spot_1_N_plus_N_plus_N_plus_N_plus_N_m1.pdb', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1')
cmd.hide('everything', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1')
cmd.show('cartoon', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1 and chain F')
cmd.show('sticks', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1 and chain Z')
cmd.color('lightblue', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1 and chain F')
cmd.color('orange', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1 and chain Z')

cmd.pseudoatom('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_0', pos=[4.901, -0.599, -2.429])
cmd.hide('nonbonded', 'lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_0')
cmd.label('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_0', '"-1.67"')
cmd.pseudoatom('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_1', pos=[5.713, -0.354, -2.863])
cmd.hide('nonbonded', 'lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_1')
cmd.label('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_1', '"-0.51"')
cmd.pseudoatom('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_2', pos=[5.575, 0.685, -2.434])
cmd.hide('nonbonded', 'lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_2')
cmd.label('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_2', '"-1.99"')
cmd.pseudoatom('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_3', pos=[5.382, 2.498, -3.886])
cmd.hide('nonbonded', 'lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_3')
cmd.label('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_3', '"-1.21"')
cmd.pseudoatom('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_4', pos=[4.216, 2.256, -5.080])
cmd.hide('nonbonded', 'lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_4')
cmd.label('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_4', '"-1.96"')
cmd.show('sticks', 'spot_1_N_plus_N_plus_N_plus_N_plus_N_m1 and chain F and resi 5')

# Candidate 2: candidates_v2/F5_ASP_SC/ARG_N_NE_NH2.pdb model 2070
# delta_hbond: -4.175, delta_fa_rep: 0.938
# Interfacial H-bonds: 3, Total energy: -4.175
cmd.load('spot_check_pdbs/spot_2_ARG_N_NE_NH2_m2070.pdb', 'spot_2_ARG_N_NE_NH2_m2070')
cmd.hide('everything', 'spot_2_ARG_N_NE_NH2_m2070')
cmd.show('cartoon', 'spot_2_ARG_N_NE_NH2_m2070 and chain F')
cmd.show('sticks', 'spot_2_ARG_N_NE_NH2_m2070 and chain Z')
cmd.color('lightblue', 'spot_2_ARG_N_NE_NH2_m2070 and chain F')
cmd.color('orange', 'spot_2_ARG_N_NE_NH2_m2070 and chain Z')

cmd.pseudoatom('lbl_spot_2_ARG_N_NE_NH2_m2070_0', pos=[4.460, 2.490, -4.829])
cmd.hide('nonbonded', 'lbl_spot_2_ARG_N_NE_NH2_m2070_0')
cmd.label('lbl_spot_2_ARG_N_NE_NH2_m2070_0', '"-1.21"')
cmd.pseudoatom('lbl_spot_2_ARG_N_NE_NH2_m2070_1', pos=[5.566, 2.003, -3.918])
cmd.hide('nonbonded', 'lbl_spot_2_ARG_N_NE_NH2_m2070_1')
cmd.label('lbl_spot_2_ARG_N_NE_NH2_m2070_1', '"-1.37"')
cmd.pseudoatom('lbl_spot_2_ARG_N_NE_NH2_m2070_2', pos=[5.811, 0.292, -2.514])
cmd.hide('nonbonded', 'lbl_spot_2_ARG_N_NE_NH2_m2070_2')
cmd.label('lbl_spot_2_ARG_N_NE_NH2_m2070_2', '"-1.59"')
cmd.show('sticks', 'spot_2_ARG_N_NE_NH2_m2070 and chain F and resi 5')

# Candidate 3: candidates_v2/F6_ASP_BB_O/N_plus_N.pdb model 236
# delta_hbond: -3.261, delta_fa_rep: 0.016
# Interfacial H-bonds: 3, Total energy: -3.261
cmd.load('spot_check_pdbs/spot_3_N_plus_N_m236.pdb', 'spot_3_N_plus_N_m236')
cmd.hide('everything', 'spot_3_N_plus_N_m236')
cmd.show('cartoon', 'spot_3_N_plus_N_m236 and chain F')
cmd.show('sticks', 'spot_3_N_plus_N_m236 and chain Z')
cmd.color('lightblue', 'spot_3_N_plus_N_m236 and chain F')
cmd.color('orange', 'spot_3_N_plus_N_m236 and chain Z')

cmd.pseudoatom('lbl_spot_3_N_plus_N_m236_0', pos=[0.026, 4.144, -4.338])
cmd.hide('nonbonded', 'lbl_spot_3_N_plus_N_m236_0')
cmd.label('lbl_spot_3_N_plus_N_m236_0', '"-0.29"')
cmd.pseudoatom('lbl_spot_3_N_plus_N_m236_1', pos=[-1.723, 2.653, -6.145])
cmd.hide('nonbonded', 'lbl_spot_3_N_plus_N_m236_1')
cmd.label('lbl_spot_3_N_plus_N_m236_1', '"-1.25"')
cmd.pseudoatom('lbl_spot_3_N_plus_N_m236_2', pos=[-2.016, 2.378, -6.958])
cmd.hide('nonbonded', 'lbl_spot_3_N_plus_N_m236_2')
cmd.label('lbl_spot_3_N_plus_N_m236_2', '"-1.72"')
cmd.show('sticks', 'spot_3_N_plus_N_m236 and chain F and resi 4+6')

# Candidate 4: candidates_v2/F6_ASP_SC/N_plus_N.pdb model 597
# delta_hbond: -2.886, delta_fa_rep: 0.843
# Interfacial H-bonds: 2, Total energy: -2.886
cmd.load('spot_check_pdbs/spot_4_N_plus_N_m597.pdb', 'spot_4_N_plus_N_m597')
cmd.hide('everything', 'spot_4_N_plus_N_m597')
cmd.show('cartoon', 'spot_4_N_plus_N_m597 and chain F')
cmd.show('sticks', 'spot_4_N_plus_N_m597 and chain Z')
cmd.color('lightblue', 'spot_4_N_plus_N_m597 and chain F')
cmd.color('orange', 'spot_4_N_plus_N_m597 and chain Z')

cmd.pseudoatom('lbl_spot_4_N_plus_N_m597_0', pos=[-5.633, -1.851, -3.772])
cmd.hide('nonbonded', 'lbl_spot_4_N_plus_N_m597_0')
cmd.label('lbl_spot_4_N_plus_N_m597_0', '"-0.98"')
cmd.pseudoatom('lbl_spot_4_N_plus_N_m597_1', pos=[-4.956, -1.561, -5.642])
cmd.hide('nonbonded', 'lbl_spot_4_N_plus_N_m597_1')
cmd.label('lbl_spot_4_N_plus_N_m597_1', '"-1.91"')
cmd.show('sticks', 'spot_4_N_plus_N_m597 and chain F and resi 6')

# Candidate 5: candidates_v2/F4_ASP_BB_O/N_plus_N.pdb model 506
# delta_hbond: -2.472, delta_fa_rep: 3.082
# Interfacial H-bonds: 2, Total energy: -2.472
cmd.load('spot_check_pdbs/spot_5_N_plus_N_m506.pdb', 'spot_5_N_plus_N_m506')
cmd.hide('everything', 'spot_5_N_plus_N_m506')
cmd.show('cartoon', 'spot_5_N_plus_N_m506 and chain F')
cmd.show('sticks', 'spot_5_N_plus_N_m506 and chain Z')
cmd.color('lightblue', 'spot_5_N_plus_N_m506 and chain F')
cmd.color('orange', 'spot_5_N_plus_N_m506 and chain Z')

cmd.pseudoatom('lbl_spot_5_N_plus_N_m506_0', pos=[0.067, 4.338, -3.624])
cmd.hide('nonbonded', 'lbl_spot_5_N_plus_N_m506_0')
cmd.label('lbl_spot_5_N_plus_N_m506_0', '"-1.22"')
cmd.pseudoatom('lbl_spot_5_N_plus_N_m506_1', pos=[0.828, 4.021, -4.422])
cmd.hide('nonbonded', 'lbl_spot_5_N_plus_N_m506_1')
cmd.label('lbl_spot_5_N_plus_N_m506_1', '"-1.25"')
cmd.show('sticks', 'spot_5_N_plus_N_m506 and chain F and resi 4')

# Candidate 6: candidates_v2/F4_ASP_BB_O/TRP_NE1_plus_GLU_wOE1.pdb model 5
# delta_hbond: -2.027, delta_fa_rep: 1.178
# Interfacial H-bonds: 2, Total energy: -2.027
cmd.load('spot_check_pdbs/spot_6_TRP_NE1_plus_GLU_wOE1_m5.pdb', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5')
cmd.hide('everything', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5')
cmd.show('cartoon', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5 and chain F')
cmd.show('sticks', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5 and chain Z')
cmd.color('lightblue', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5 and chain F')
cmd.color('orange', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5 and chain Z')

cmd.pseudoatom('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_0', pos=[0.899, 4.041, -4.247])
cmd.hide('nonbonded', 'lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_0')
cmd.label('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_0', '"-1.17"')
cmd.pseudoatom('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_1', pos=[-0.041, 4.151, -3.746])
cmd.hide('nonbonded', 'lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_1')
cmd.label('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_1', '"-0.86"')
cmd.show('sticks', 'spot_6_TRP_NE1_plus_GLU_wOE1_m5 and chain F and resi 4')

# Candidate 7: candidates_v2/F5_ASP_BB_O/GLN_wOE1.pdb model 869
# delta_hbond: -1.519, delta_fa_rep: 15.343
# Interfacial H-bonds: 1, Total energy: -1.519
cmd.load('spot_check_pdbs/spot_7_GLN_wOE1_m869.pdb', 'spot_7_GLN_wOE1_m869')
cmd.hide('everything', 'spot_7_GLN_wOE1_m869')
cmd.show('cartoon', 'spot_7_GLN_wOE1_m869 and chain F')
cmd.show('sticks', 'spot_7_GLN_wOE1_m869 and chain Z')
cmd.color('lightblue', 'spot_7_GLN_wOE1_m869 and chain F')
cmd.color('orange', 'spot_7_GLN_wOE1_m869 and chain Z')

cmd.pseudoatom('lbl_spot_7_GLN_wOE1_m869_0', pos=[1.397, 0.020, -6.198])
cmd.hide('nonbonded', 'lbl_spot_7_GLN_wOE1_m869_0')
cmd.label('lbl_spot_7_GLN_wOE1_m869_0', '"-1.52"')
cmd.show('sticks', 'spot_7_GLN_wOE1_m869 and chain F and resi 5')

# Candidate 8: candidates_v2/F2_TYR_BB_N/SER_OG.pdb model 2653
# delta_hbond: -1.358, delta_fa_rep: 2.331
# Interfacial H-bonds: 1, Total energy: -1.358
cmd.load('spot_check_pdbs/spot_8_SER_OG_m2653.pdb', 'spot_8_SER_OG_m2653')
cmd.hide('everything', 'spot_8_SER_OG_m2653')
cmd.show('cartoon', 'spot_8_SER_OG_m2653 and chain F')
cmd.show('sticks', 'spot_8_SER_OG_m2653 and chain Z')
cmd.color('lightblue', 'spot_8_SER_OG_m2653 and chain F')
cmd.color('orange', 'spot_8_SER_OG_m2653 and chain Z')

cmd.pseudoatom('lbl_spot_8_SER_OG_m2653_0', pos=[3.622, -0.690, 4.342])
cmd.hide('nonbonded', 'lbl_spot_8_SER_OG_m2653_0')
cmd.label('lbl_spot_8_SER_OG_m2653_0', '"-1.36"')
cmd.show('sticks', 'spot_8_SER_OG_m2653 and chain F and resi 2')

# Candidate 9: candidates_v2/F6_ASP_BB_O/ASP_wOD1.pdb model 360
# delta_hbond: -1.239, delta_fa_rep: 0.058
# Interfacial H-bonds: 1, Total energy: -1.239
cmd.load('spot_check_pdbs/spot_9_ASP_wOD1_m360.pdb', 'spot_9_ASP_wOD1_m360')
cmd.hide('everything', 'spot_9_ASP_wOD1_m360')
cmd.show('cartoon', 'spot_9_ASP_wOD1_m360 and chain F')
cmd.show('sticks', 'spot_9_ASP_wOD1_m360 and chain Z')
cmd.color('lightblue', 'spot_9_ASP_wOD1_m360 and chain F')
cmd.color('orange', 'spot_9_ASP_wOD1_m360 and chain Z')

cmd.pseudoatom('lbl_spot_9_ASP_wOD1_m360_0', pos=[-2.021, 2.336, -6.833])
cmd.hide('nonbonded', 'lbl_spot_9_ASP_wOD1_m360_0')
cmd.label('lbl_spot_9_ASP_wOD1_m360_0', '"-1.24"')
cmd.show('sticks', 'spot_9_ASP_wOD1_m360 and chain F and resi 6')

# Candidate 10: candidates_v2/F5_ASP_BB_O/ASP_wOD1.pdb model 1195
# delta_hbond: -1.126, delta_fa_rep: 0.158
# Interfacial H-bonds: 1, Total energy: -1.126
cmd.load('spot_check_pdbs/spot_10_ASP_wOD1_m1195.pdb', 'spot_10_ASP_wOD1_m1195')
cmd.hide('everything', 'spot_10_ASP_wOD1_m1195')
cmd.show('cartoon', 'spot_10_ASP_wOD1_m1195 and chain F')
cmd.show('sticks', 'spot_10_ASP_wOD1_m1195 and chain Z')
cmd.color('lightblue', 'spot_10_ASP_wOD1_m1195 and chain F')
cmd.color('orange', 'spot_10_ASP_wOD1_m1195 and chain Z')

cmd.pseudoatom('lbl_spot_10_ASP_wOD1_m1195_0', pos=[0.396, -0.850, -6.021])
cmd.hide('nonbonded', 'lbl_spot_10_ASP_wOD1_m1195_0')
cmd.label('lbl_spot_10_ASP_wOD1_m1195_0', '"-1.13"')
cmd.show('sticks', 'spot_10_ASP_wOD1_m1195 and chain F and resi 5')

# All interfacial H-bonds as CGO cylinders
hbond_cgo = [
    CYLINDER, 4.850, -1.180, -2.024, 4.953, -0.017, -2.835, 0.08, 0.17, 0.83, 0.20, 0.17, 0.83, 0.20,
    CYLINDER, 6.312, -0.740, -2.805, 5.115, 0.031, -2.921, 0.08, 0.74, 0.26, 0.20, 0.74, 0.26, 0.20,
    CYLINDER, 6.061, 1.131, -2.033, 5.088, 0.239, -2.836, 0.08, 0.00, 1.00, 0.20, 0.00, 1.00, 0.20,
    CYLINDER, 6.088, 3.000, -3.620, 4.676, 1.995, -4.152, 0.08, 0.40, 0.60, 0.20, 0.40, 0.60, 0.20,
    CYLINDER, 3.990, 2.566, -5.769, 4.442, 1.946, -4.391, 0.08, 0.02, 0.98, 0.20, 0.02, 0.98, 0.20,
    CYLINDER, 4.430, 2.988, -5.316, 4.491, 1.993, -4.341, 0.08, 0.40, 0.60, 0.20, 0.40, 0.60, 0.20,
    CYLINDER, 6.421, 2.111, -3.678, 4.712, 1.896, -4.159, 0.08, 0.31, 0.69, 0.20, 0.31, 0.69, 0.20,
    CYLINDER, 6.486, 0.424, -2.176, 5.135, 0.161, -2.852, 0.08, 0.20, 0.80, 0.20, 0.20, 0.80, 0.20,
    CYLINDER, -0.479, 4.524, -5.066, 0.532, 3.763, -3.610, 0.08, 0.85, 0.15, 0.20, 0.85, 0.15, 0.20,
    CYLINDER, -1.534, 3.381, -6.131, -1.913, 1.924, -6.159, 0.08, 0.38, 0.62, 0.20, 0.38, 0.62, 0.20,
    CYLINDER, -2.060, 2.888, -7.594, -1.971, 1.869, -6.322, 0.08, 0.14, 0.86, 0.20, 0.14, 0.86, 0.20,
    CYLINDER, -6.175, -2.178, -4.303, -5.091, -1.525, -3.242, 0.08, 0.51, 0.49, 0.20, 0.51, 0.49, 0.20,
    CYLINDER, -5.570, -1.642, -6.017, -4.342, -1.480, -5.267, 0.08, 0.05, 0.95, 0.20, 0.05, 0.95, 0.20,
    CYLINDER, -0.406, 4.874, -3.781, 0.540, 3.802, -3.467, 0.08, 0.39, 0.61, 0.20, 0.39, 0.61, 0.20,
    CYLINDER, 0.963, 4.303, -5.217, 0.692, 3.739, -3.627, 0.08, 0.37, 0.63, 0.20, 0.37, 0.63, 0.20,
    CYLINDER, 1.093, 4.339, -4.902, 0.706, 3.743, -3.592, 0.08, 0.42, 0.58, 0.20, 0.42, 0.58, 0.20,
    CYLINDER, -0.600, 4.537, -4.000, 0.518, 3.765, -3.492, 0.08, 0.57, 0.43, 0.20, 0.57, 0.43, 0.20,
    CYLINDER, 2.009, 0.086, -6.566, 0.786, -0.046, -5.830, 0.08, 0.24, 0.76, 0.20, 0.24, 0.76, 0.20,
    CYLINDER, 3.188, -0.388, 3.683, 4.056, -0.991, 5.002, 0.08, 0.32, 0.68, 0.20, 0.32, 0.68, 0.20,
    CYLINDER, -2.070, 2.811, -7.369, -1.972, 1.861, -6.297, 0.08, 0.38, 0.62, 0.20, 0.38, 0.62, 0.20,
    CYLINDER, 0.206, -1.480, -6.248, 0.586, -0.220, -5.795, 0.08, 0.44, 0.56, 0.20, 0.44, 0.56, 0.20,
]
cmd.load_cgo(hbond_cgo, 'interfacial_hbonds')

# Color legend: Green = strong H-bond (< -1.5), Yellow = medium, Red = weak (> -0.5)

# Per-candidate H-bond CGO objects
hb_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_cgo = [
    CYLINDER, 4.850, -1.180, -2.024, 4.953, -0.017, -2.835, 0.08, 0.17, 0.83, 0.20, 0.17, 0.83, 0.20,
    CYLINDER, 6.312, -0.740, -2.805, 5.115, 0.031, -2.921, 0.08, 0.74, 0.26, 0.20, 0.74, 0.26, 0.20,
    CYLINDER, 6.061, 1.131, -2.033, 5.088, 0.239, -2.836, 0.08, 0.00, 1.00, 0.20, 0.00, 1.00, 0.20,
    CYLINDER, 6.088, 3.000, -3.620, 4.676, 1.995, -4.152, 0.08, 0.40, 0.60, 0.20, 0.40, 0.60, 0.20,
    CYLINDER, 3.990, 2.566, -5.769, 4.442, 1.946, -4.391, 0.08, 0.02, 0.98, 0.20, 0.02, 0.98, 0.20,
]
cmd.load_cgo(hb_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_cgo, 'hb_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1')
hb_spot_2_ARG_N_NE_NH2_m2070_cgo = [
    CYLINDER, 4.430, 2.988, -5.316, 4.491, 1.993, -4.341, 0.08, 0.40, 0.60, 0.20, 0.40, 0.60, 0.20,
    CYLINDER, 6.421, 2.111, -3.678, 4.712, 1.896, -4.159, 0.08, 0.31, 0.69, 0.20, 0.31, 0.69, 0.20,
    CYLINDER, 6.486, 0.424, -2.176, 5.135, 0.161, -2.852, 0.08, 0.20, 0.80, 0.20, 0.20, 0.80, 0.20,
]
cmd.load_cgo(hb_spot_2_ARG_N_NE_NH2_m2070_cgo, 'hb_spot_2_ARG_N_NE_NH2_m2070')
hb_spot_3_N_plus_N_m236_cgo = [
    CYLINDER, -0.479, 4.524, -5.066, 0.532, 3.763, -3.610, 0.08, 0.85, 0.15, 0.20, 0.85, 0.15, 0.20,
    CYLINDER, -1.534, 3.381, -6.131, -1.913, 1.924, -6.159, 0.08, 0.38, 0.62, 0.20, 0.38, 0.62, 0.20,
    CYLINDER, -2.060, 2.888, -7.594, -1.971, 1.869, -6.322, 0.08, 0.14, 0.86, 0.20, 0.14, 0.86, 0.20,
]
cmd.load_cgo(hb_spot_3_N_plus_N_m236_cgo, 'hb_spot_3_N_plus_N_m236')
hb_spot_4_N_plus_N_m597_cgo = [
    CYLINDER, -6.175, -2.178, -4.303, -5.091, -1.525, -3.242, 0.08, 0.51, 0.49, 0.20, 0.51, 0.49, 0.20,
    CYLINDER, -5.570, -1.642, -6.017, -4.342, -1.480, -5.267, 0.08, 0.05, 0.95, 0.20, 0.05, 0.95, 0.20,
]
cmd.load_cgo(hb_spot_4_N_plus_N_m597_cgo, 'hb_spot_4_N_plus_N_m597')
hb_spot_5_N_plus_N_m506_cgo = [
    CYLINDER, -0.406, 4.874, -3.781, 0.540, 3.802, -3.467, 0.08, 0.39, 0.61, 0.20, 0.39, 0.61, 0.20,
    CYLINDER, 0.963, 4.303, -5.217, 0.692, 3.739, -3.627, 0.08, 0.37, 0.63, 0.20, 0.37, 0.63, 0.20,
]
cmd.load_cgo(hb_spot_5_N_plus_N_m506_cgo, 'hb_spot_5_N_plus_N_m506')
hb_spot_6_TRP_NE1_plus_GLU_wOE1_m5_cgo = [
    CYLINDER, 1.093, 4.339, -4.902, 0.706, 3.743, -3.592, 0.08, 0.42, 0.58, 0.20, 0.42, 0.58, 0.20,
    CYLINDER, -0.600, 4.537, -4.000, 0.518, 3.765, -3.492, 0.08, 0.57, 0.43, 0.20, 0.57, 0.43, 0.20,
]
cmd.load_cgo(hb_spot_6_TRP_NE1_plus_GLU_wOE1_m5_cgo, 'hb_spot_6_TRP_NE1_plus_GLU_wOE1_m5')
hb_spot_7_GLN_wOE1_m869_cgo = [
    CYLINDER, 2.009, 0.086, -6.566, 0.786, -0.046, -5.830, 0.08, 0.24, 0.76, 0.20, 0.24, 0.76, 0.20,
]
cmd.load_cgo(hb_spot_7_GLN_wOE1_m869_cgo, 'hb_spot_7_GLN_wOE1_m869')
hb_spot_8_SER_OG_m2653_cgo = [
    CYLINDER, 3.188, -0.388, 3.683, 4.056, -0.991, 5.002, 0.08, 0.32, 0.68, 0.20, 0.32, 0.68, 0.20,
]
cmd.load_cgo(hb_spot_8_SER_OG_m2653_cgo, 'hb_spot_8_SER_OG_m2653')
hb_spot_9_ASP_wOD1_m360_cgo = [
    CYLINDER, -2.070, 2.811, -7.369, -1.972, 1.861, -6.297, 0.08, 0.38, 0.62, 0.20, 0.38, 0.62, 0.20,
]
cmd.load_cgo(hb_spot_9_ASP_wOD1_m360_cgo, 'hb_spot_9_ASP_wOD1_m360')
hb_spot_10_ASP_wOD1_m1195_cgo = [
    CYLINDER, 0.206, -1.480, -6.248, 0.586, -0.220, -5.795, 0.08, 0.44, 0.56, 0.20, 0.44, 0.56, 0.20,
]
cmd.load_cgo(hb_spot_10_ASP_wOD1_m1195_cgo, 'hb_spot_10_ASP_wOD1_m1195')

# Create scenes for each candidate
# Use PgUp/PgDn or scene buttons to navigate

# Scene 1: N_plus_N_plus_N_plus_N_plus_N model 1
# dHbond: -7.345, 5 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_1_N_plus_N_plus_N_plus_N_plus_N_m1')
cmd.enable('hb_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1')
cmd.enable('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_0')
cmd.enable('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_1')
cmd.enable('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_2')
cmd.enable('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_3')
cmd.enable('lbl_spot_1_N_plus_N_plus_N_plus_N_plus_N_m1_4')
cmd.zoom('spot_1_N_plus_N_plus_N_plus_N_plus_N_m1', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_1', 'store', message='N_plus_N_plus_N_plus_N_plus_N m1: dHbond=-7.34')

# Scene 2: ARG_N_NE_NH2 model 2070
# dHbond: -4.175, 3 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_2_ARG_N_NE_NH2_m2070')
cmd.enable('hb_spot_2_ARG_N_NE_NH2_m2070')
cmd.enable('lbl_spot_2_ARG_N_NE_NH2_m2070_0')
cmd.enable('lbl_spot_2_ARG_N_NE_NH2_m2070_1')
cmd.enable('lbl_spot_2_ARG_N_NE_NH2_m2070_2')
cmd.zoom('spot_2_ARG_N_NE_NH2_m2070', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_2', 'store', message='ARG_N_NE_NH2 m2070: dHbond=-4.18')

# Scene 3: N_plus_N model 236
# dHbond: -3.261, 3 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_3_N_plus_N_m236')
cmd.enable('hb_spot_3_N_plus_N_m236')
cmd.enable('lbl_spot_3_N_plus_N_m236_0')
cmd.enable('lbl_spot_3_N_plus_N_m236_1')
cmd.enable('lbl_spot_3_N_plus_N_m236_2')
cmd.zoom('spot_3_N_plus_N_m236', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_3', 'store', message='N_plus_N m236: dHbond=-3.26')

# Scene 4: N_plus_N model 597
# dHbond: -2.886, 2 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_4_N_plus_N_m597')
cmd.enable('hb_spot_4_N_plus_N_m597')
cmd.enable('lbl_spot_4_N_plus_N_m597_0')
cmd.enable('lbl_spot_4_N_plus_N_m597_1')
cmd.zoom('spot_4_N_plus_N_m597', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_4', 'store', message='N_plus_N m597: dHbond=-2.89')

# Scene 5: N_plus_N model 506
# dHbond: -2.472, 2 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_5_N_plus_N_m506')
cmd.enable('hb_spot_5_N_plus_N_m506')
cmd.enable('lbl_spot_5_N_plus_N_m506_0')
cmd.enable('lbl_spot_5_N_plus_N_m506_1')
cmd.zoom('spot_5_N_plus_N_m506', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_5', 'store', message='N_plus_N m506: dHbond=-2.47')

# Scene 6: TRP_NE1_plus_GLU_wOE1 model 5
# dHbond: -2.027, 2 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_6_TRP_NE1_plus_GLU_wOE1_m5')
cmd.enable('hb_spot_6_TRP_NE1_plus_GLU_wOE1_m5')
cmd.enable('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_0')
cmd.enable('lbl_spot_6_TRP_NE1_plus_GLU_wOE1_m5_1')
cmd.zoom('spot_6_TRP_NE1_plus_GLU_wOE1_m5', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_6', 'store', message='TRP_NE1_plus_GLU_wOE1 m5: dHbond=-2.03')

# Scene 7: GLN_wOE1 model 869
# dHbond: -1.519, 1 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_7_GLN_wOE1_m869')
cmd.enable('hb_spot_7_GLN_wOE1_m869')
cmd.enable('lbl_spot_7_GLN_wOE1_m869_0')
cmd.zoom('spot_7_GLN_wOE1_m869', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_7', 'store', message='GLN_wOE1 m869: dHbond=-1.52')

# Scene 8: SER_OG model 2653
# dHbond: -1.358, 1 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_8_SER_OG_m2653')
cmd.enable('hb_spot_8_SER_OG_m2653')
cmd.enable('lbl_spot_8_SER_OG_m2653_0')
cmd.zoom('spot_8_SER_OG_m2653', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_8', 'store', message='SER_OG m2653: dHbond=-1.36')

# Scene 9: ASP_wOD1 model 360
# dHbond: -1.239, 1 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_9_ASP_wOD1_m360')
cmd.enable('hb_spot_9_ASP_wOD1_m360')
cmd.enable('lbl_spot_9_ASP_wOD1_m360_0')
cmd.zoom('spot_9_ASP_wOD1_m360', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_9', 'store', message='ASP_wOD1 m360: dHbond=-1.24')

# Scene 10: ASP_wOD1 model 1195
# dHbond: -1.126, 1 H-bonds
cmd.disable('spot_*')
cmd.disable('hb_spot_*')
cmd.disable('lbl_*')
cmd.disable('interfacial_hbonds')
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
cmd.enable('spot_10_ASP_wOD1_m1195')
cmd.enable('hb_spot_10_ASP_wOD1_m1195')
cmd.enable('lbl_spot_10_ASP_wOD1_m1195_0')
cmd.zoom('spot_10_ASP_wOD1_m1195', buffer=5)
cmd.enable('spot_checks')
cmd.enable('hbond_cgos')
cmd.enable('hbond_labels')
util.cnc('all', _self=cmd)
cmd.scene('spot_10', 'store', message='ASP_wOD1 m1195: dHbond=-1.13')

# ======================================================================
# SUMMARY
# ======================================================================
# Candidate                                |   dHbond |  #HB |    IntfE
# ----------------------------------------------------------------------
# N_plus_N_plus_N_plus_N_plus_N.pdb        |   -7.345 |    5 |   -7.345
# ARG_N_NE_NH2.pdb                         |   -4.175 |    3 |   -4.175
# N_plus_N.pdb                             |   -3.261 |    3 |   -3.261
# N_plus_N.pdb                             |   -2.886 |    2 |   -2.886
# N_plus_N.pdb                             |   -2.472 |    2 |   -2.472
# TRP_NE1_plus_GLU_wOE1.pdb                |   -2.027 |    2 |   -2.027
# GLN_wOE1.pdb                             |   -1.519 |    1 |   -1.519
# SER_OG.pdb                               |   -1.358 |    1 |   -1.358
# ASP_wOD1.pdb                             |   -1.239 |    1 |   -1.239
# ASP_wOD1.pdb                             |   -1.126 |    1 |   -1.126

# Display settings
cmd.bg_color('black')
cmd.set('ray_shadows', 'off')
cmd.set('specular', 0.2)
cmd.set('scene_buttons', 1)
cmd.set('scene_loop', 1)

# Group all spot-check objects
cmd.group('spot_checks', 'spot_*')
cmd.group('hbond_labels', 'lbl_*')
cmd.group('hbond_cgos', 'hb_spot_*')

# Recall first scene
cmd.scene('spot_1', 'recall')

print('Loaded 10 spot-check candidates')
print('')
print('NAVIGATION:')
print('  PgUp/PgDn    - Previous/Next scene')
print('  Scene buttons - Click numbered buttons at bottom')
print('  scene spot_N  - Jump to specific scene (N=1-10)')
print('')
print('SHOW ALL:')
print('  enable spot_checks; enable hbond_cgos; enable interfacial_hbonds')
print('')